export const picture = [
  {
    id: 1,
    image: require("../assets/picture2.jpg"),
  },
  {
    id: 2,
    image: require("../assets/picture3.jpg"),
  },
  {
    id: 3,
    image: require("../assets/picture4.jpg"),
  },
  {
    id: 4,
    image: require("../assets/picture5.jpg"),
  },
  {
    id: 5,
    image: require("../assets/picture6.jpg"),
  },
  {
    id: 6,
    image: require("../assets/picture1.png"),
  },
];
export const orderAgain = [
  {
    id: 1,
    pic: require("../assets/images/3819.jpg"),
    name: "Sultan Dine",
    rating: 4.5,
    sell: "(2000+)",
    taka: " ৳৳ . ৳ 150 minimum",
    type: "Biriyani",
    time: "15-30 mins",
    fee: "8",
  },
];
export const dishes = [
  {
    id: 1,
    pic: require("../assets/images/3819.jpg"),
    name: "Sultan Dine",
    rating: 4.5,
    sell: "(2000+)",
    taka: " ৳৳ . ৳ 150 minimum",
    type: "Biriyani",
    time: "15-30 mins",
    fee: "8",
    distance: "699m away",
    pickTime: "Pick up in 10 min",
  },
  {
    id: 1,
    pic: require("../assets/images/a.jpeg"),
    name: "Fish Curry",
    rating: 3.5,
    sell: "(100+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Dessert",
    time: "15-30 mins",
    fee: "8",
    distance: "700m away",
    pickTime: "Pick up in 12 min",
  },
  {
    id: 2,
    pic: require("../assets/images/aa.jpeg"),
    name: "Petuk Restaurant",
    rating: 3.8,
    sell: "(1000+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Bangladeshi",
    time: "15-30 mins",
    fee: "8",
    distance: "1Km away",
    pickTime: "Pick up in 15 min",
  },
  {
    id: 3,
    pic: require("../assets/images/b.jpeg"),
    name: "Fish Curry",
    rating: 4.1,
    sell: "(1000+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Dessert",
    time: "15-30 mins",
    fee: "8",
    distance: "1.5Km away",
    pickTime: "Pick up in 20 min",
  },
  {
    id: 4,
    pic: require("../assets/images/bb.jpeg"),
    name: "Burger Lite",
    rating: 4.1,
    sell: "(1000+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Dessert",
    time: "15-30 mins",
    fee: "8",
    distance: "2Km away",
    pickTime: "Pick up in 30 min",
  },
];

export const lunch = [
  {
    id: 1,
    pic: require("../assets/images/3819.jpg"),
    name: "Sultan Dine",
    rating: 4.5,
    sell: "(2000+)",
    taka: " ৳৳ . ৳ 150 minimum",
    type: "Biriyani",
    time: "15-30 mins",
    fee: "8",
  },
  {
    id: 1,
    pic: require("../assets/images/c.jpeg"),
    name: "Fish Curry",
    rating: 3.5,
    sell: "(100+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Dessert",
    time: "15-30 mins",
    fee: "8",
  },
  {
    id: 2,
    pic: require("../assets/images/cc.jpeg"),
    name: "Petuk Restaurant",
    rating: 3.8,
    sell: "(1000+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Bangladeshi",
    time: "15-30 mins",
    fee: "8",
  },
  {
    id: 3,
    pic: require("../assets/images/b.jpeg"),
    name: "Fish Curry",
    rating: 4.1,
    sell: "(1000+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Dessert",
    time: "15-30 mins",
    fee: "8",
  },
  {
    id: 4,
    pic: require("../assets/images/bb.jpeg"),
    name: "Burger Lite",
    rating: 4.1,
    sell: "(1000+)",
    taka: " ৳৳ . ৳ 50 minimum",
    type: "Dessert",
    time: "15-30 mins",
    fee: "8",
  },
];
